export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL'
export const GET_LOGOUT_SUCCESS = "GET_LOGOUT_SUCCESS"
